### ISSUE TITLE
y el specto--y tiene el specto

### ISSUE THREAD

**Issue by fhxshrs** [rdrg109/subtitles-npcr#1097]
https://github.com/rdrg109/subtitles-npcr/blob/4d007f0d7f48ebda5b35791f3cf6b5f2267f794b/sentences/45-text-1.yaml#L236C7-L236C23

**Comment by rdrg109** [comment]
@fhxshrs I think that in this context, "有" in "还有" doesn't have the context of "having", but "还有" translates to "moreover" (in Spanish, "ademas"). 

In Spanish, we say "X tiene el aspecto Y" when we want to describe the physical appearance of someone or something.

> Así como millones en redes sociales, tú también quedarás con la boca abierta cuando veas a esta enorme tortuga que es la nueva atracción en un río de los Estados Unidos ¿por qué? Pues, resulta que la mordedora **tiene un aspecto aterrador**, al punto que para muchos tiene la apariencia de una bestia sacada de los tiempos cuando los dinosaurios caminaban sobre la Tierra, por lo que rápidamente se hizo viral. Retrieved from [El Comercio](https://mag.elcomercio.pe/usa/tendencias-us/video-viral-impresionante-tortuga-aspecto-de-dinosaurio-es-nueva-sensacion-en-rio-de-eeuu-youtube-estados-unidos-nnda-nnrt-noticia/)

In this context, the manager doesn't refer the physical appearance of the other person but the aspect of the work experience which he considers is a good thing, so I think that this shouldn't be corrected.

Let me know if you don't agree with me.

**Comment by rdrg109** [comment]
@fhxshrs I've been thinking more on this. Please omit my previous message. I think there are two possible translations for "还有这方面的工作经验。" with two different meanings.

1. "Moreover, there's the aspect of your work experience." (Here, the speaker feels satisfied with Ma Dawei just having work experience regardless of the area he worked before)
2. "Moreover, you have work experience on the same aspect" (of this company). (Here, the speaker feels satisfied with Ma Dawei because he has worked on something that is strongly related with the position the company is hiring for)

@fhxshrs which do you think is most suitable?

**Comment by fhxshrs** [comment]
@rdrg109  Yes, what I meant to say was the second meaning. And thanks for letting me know of the Spanish phrase.

**Comment by rdrg109** [comment]
c310f0d

**Comment by fhxshrs** [comment]
@rdrg109 那应该是cuenta con吧，因为是“您”。

**Comment by rdrg109** [comment]
c9c180e
