### ISSUE TITLE
there is none -- is a no-go

### ISSUE THREAD

**Issue by fhxshrs** [rdrg109/subtitles-npcr#1114]
https://github.com/rdrg109/subtitles-npcr/blob/1c56c5a8099a2253b50c5d443937efd985125c82/sentences/46-text-1.yaml#L327-L331

**Comment by rdrg109** [comment]
@fhxshrs From my understanding,  the speaker of this sentence just want to express that there are no classes this Saturday, but normally, the calligraphy classes take place in Saturday. Am I right?

Here's the part of the book where that sentence appear (just in case someone needs more context)

![image](https://github.com/rdrg109/subtitles-npcr/assets/74389646/1f5bc1e3-2f26-4d43-9d02-19be3658edda)

**Comment by fhxshrs** [comment]
@rdrg109 “星期六这一天是没有了”这句话在这里的意思是孩子的星期六要么上电脑辅导课，要么上书法班，课外时间全被这些辅导班占据了，所以没有自己玩的时间，所以“没有”指的是“没有玩的时间”。

**Comment by rdrg109** [comment]
@fhxshrs I understand what you mean. I think a learner could interpret this in two different ways

* (The meaning that you explained) The teacher emphasized that Saturday (the day they were in) there's no time to play because the kid has to attend multiple classes.
* The teacher said to the kid that he doesn't need to attend classes as a joke, and the teacher knows that the kid won't believe this because the kid knows that his parents take the final decision, therefore the teacher just said that joke to express the kid that he knows that the kid wishes that were no classes.

I have considered the one that you suggested: e372333 (i.e. the first one) For the record, here's the relevant part of the video. 

[output.webm](https://github.com/rdrg109/subtitles-npcr/assets/74389646/993fc569-b382-4b41-8c09-3b450f2d223b)
