### ISSUE TITLE
originally -- had

### ISSUE THREAD

**Issue by fhxshrs** [rdrg109/subtitles-npcr#1117]
https://github.com/rdrg109/subtitles-npcr/blob/bab51df130ecfd01b9f213c863875188d028fc4a/sentences/46-text-2.yaml#L112-L116

**Comment by rdrg109** [comment]
@fhxshrs I've kept "originally" but I've added "had" as you suggested: 786628e. I did it  this way because by showing "originally", we can let Chinese learners know that "originally" is a possible translation of "本来". Also, "had originally"  is a common expression. Google shows 3820 results when searching `site:bbc.com "had originally"` and 5840 results when searching `site:theguardian.com "had originally"`.

If you don't agree with this change, please let me know.
