### ISSUE TITLE
disagrees with everyone -- sees that no one agrees with her

### ISSUE THREAD

**Issue by fhxshrs** [rdrg109/subtitles-npcr#1118]
https://github.com/rdrg109/subtitles-npcr/blob/bab51df130ecfd01b9f213c863875188d028fc4a/sentences/46-text-2.yaml#L147-L151

**Comment by rdrg109** [comment]
@fhxshrs I think `en` should include "everyone" so that we can show "大家" with "everyone" with the same color. If we used "no one", we wouldn't be able to show a word in `en` with the same color as "大家".

I've made some changes: 6858a119b3db675e3b485cc13ccf8515ff9aa12d and I've introduced a [new guideline](https://github.com/rdrg109/subtitles-npcr/blob/b98d38041e13371c25d650b7eafe3e746eb9bdab/docs/guidelines.org#3-show-as-much-direct-translations-as-possible). If you don't agree with these changes, please let me know.
