### ISSUE TITLE
我告诉她：

### ISSUE THREAD

**Issue by fhxshrs** [rdrg109/subtitles-npcr#988]
https://github.com/rdrg109/subtitles-npcr/blob/8f90d8f7dfb2ec80bfe2729b2e398b85b3d6800d/sentences/46-text-2.yaml#L242-L246

**Comment by rdrg109** [comment]
我告诉她 appears in [El Nuevo Libro de Chino Práctico (Spanish) (vol. 4) (ed. 1)](https://wikidata.org/wiki/Q118106264), but does not appear in the video. 第一，要听老师的话 appear in both of them. I've created two sentences: one for the first part and one for the second part so that we can show the first sentence in the text and reuse the second sentence in the text and the video.

I added 我告诉她 in a previous commit a0caf7f7621874a86a0af4c6fe2e5d9741842911. I've now added `context` indicators and `pinyin`, `en` and `es`: 0225606

This issue is similar to what happened in https://github.com/rdrg109/subtitles-npcr/issues/986#issuecomment-1709132012 https://github.com/rdrg109/subtitles-npcr/issues/987#issuecomment-1709137275

[output.webm](https://github.com/rdrg109/subtitles-npcr/assets/74389646/c3d91f70-7d84-4bfc-ac83-334d75da8faa)

![image](https://github.com/rdrg109/subtitles-npcr/assets/74389646/b570fcde-f948-4c97-be1e-4b27e0e51544)
