### ISSUE TITLE
女儿说：

### ISSUE THREAD

**Issue by fhxshrs** [rdrg109/subtitles-npcr#989]
https://github.com/rdrg109/subtitles-npcr/blob/8f90d8f7dfb2ec80bfe2729b2e398b85b3d6800d/sentences/46-text-2.yaml#L262-L266

**Comment by rdrg109** [comment]
女儿说： appears in [El Nuevo Libro de Chino Práctico (Spanish) (vol. 4) (ed. 1)](https://wikidata.org/wiki/Q118106264), but does not appear in the video. 你们放心，这四条我保证做到 appear in both of them. I've created two sentences: one for the first part and one for the second part so that we can show the first sentence in the text and reuse the second sentence in the text and the video.

I added the 女儿说 in a previous commit . I've now added `pinyin`, `en`, `es` and `context` to that sentence: 3ddb4c8

This issue is similar to what happened in https://github.com/rdrg109/subtitles-npcr/issues/986#issuecomment-1709132012 https://github.com/rdrg109/subtitles-npcr/issues/987#issuecomment-1709137275 https://github.com/rdrg109/subtitles-npcr/issues/988#issuecomment-1709164737

![image](https://github.com/rdrg109/subtitles-npcr/assets/74389646/c66753c3-72e7-4406-8fa1-eb4b37b0cc24)

[output.webm](https://github.com/rdrg109/subtitles-npcr/assets/74389646/02b50b5d-d27c-43cc-954e-e53fb50fe96b)
