### ISSUE TITLE
她说：

### ISSUE THREAD

**Issue by fhxshrs** [rdrg109/subtitles-npcr#991]
https://github.com/rdrg109/subtitles-npcr/blob/8f90d8f7dfb2ec80bfe2729b2e398b85b3d6800d/sentences/46-text-2.yaml#L307-L311

**Comment by rdrg109** [comment]
她说 appears in [El Nuevo Libro de Chino Práctico (Spanish) (vol. 4) (ed. 1)](https://wikidata.org/wiki/Q118106264), but does not appear in the video. 怎么没有消息呢？ appear in both of them. I've created two sentences: one for the first part and one for the second part so that we can show the first sentence in the text and reuse the second sentence in the text and the video.

I added 她说 in a previous commit a0caf7f7621874a86a0af4c6fe2e5d9741842911. I've now added `pinyin`, `en`, `es` and `context` to that sentence: 24ef95b

This issue is similar to what happened in https://github.com/rdrg109/subtitles-npcr/issues/986#issuecomment-1709132012 https://github.com/rdrg109/subtitles-npcr/issues/987#issuecomment-1709137275 https://github.com/rdrg109/subtitles-npcr/issues/988#issuecomment-1709164737 https://github.com/rdrg109/subtitles-npcr/issues/989#issuecomment-1709174150
